name: Go
on:
  push:
    tags:
    - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.x

    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: 'master'
        fetch-depth: '0'

    - name: Generate Git log
      run: |
        git fetch origin +refs/tags/*:refs/tags/*
        echo "Current Tag: ${GITHUB_REF}"
        git checkout ${GITHUB_REF} -b compile
        GITVER=$(git describe --tags)
        PREVVER=$(git describe --tags --abbrev=0 ${GITVER}~1)
        git log --oneline ${PREVVER}..${GITVER} > gittaglogs.txt

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        bash scripts/make_release.sh gzip amd64
        bash scripts/make_release.sh gzip amd64 purego
        bash scripts/make_release.sh gzip arm64 purego
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          cloud-torrent_linux_amd64.gz
          cloud-torrent_linux_amd64_static.gz
          cloud-torrent_linux_arm64_static.gz
        prerelease: true
        draft: false
        body_path: gittaglogs.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

